I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/ActionEditor.rpy", line 38, in script
    init python in _viewers:
  File "game/ActionEditor.rpy", line 38, in script
    init python in _viewers:
  File "game/ActionEditor.rpy", line 49, in <module>
    euler_slerp = renpy.display.accelerator.quaternion
AttributeError: module 'renpy.display.accelerator' has no attribute 'quaternion'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\jfarn\Downloads\renpy-8.0.3-sdk\renpy\bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "C:\Users\jfarn\Downloads\renpy-8.0.3-sdk\renpy\main.py", line 558, in main
    renpy.game.context().run(node)
  File "game/ActionEditor.rpy", line 38, in script
    init python in _viewers:
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 441, in raise_
  File "game/ActionEditor.rpy", line 38, in script
    init python in _viewers:
  File "C:\Users\jfarn\Downloads\renpy-8.0.3-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\jfarn\Downloads\renpy-8.0.3-sdk\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/ActionEditor.rpy", line 49, in <module>
    euler_slerp = renpy.display.accelerator.quaternion
AttributeError: module 'renpy.display.accelerator' has no attribute 'quaternion'

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.3.22090809
Yugino_test 1.0
Fri Jun 23 11:15:07 2023
